name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  build-push-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Tag
        id: env-tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "tag=prod-latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "tag=acceptance" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "tag=test" >> $GITHUB_OUTPUT
          fi

      - name: Set API URL
        id: api-url
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "url=https://api.diagramming.com/" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "url=https://acceptance.api.diagramming.com/" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "url=https://test.api.diagramming.com/" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VITE_BACKEND_API_URL=${{ steps.api-url.outputs.url }}
          tags: |
            ghcr.io/joeyhofman/webdev-showcase-client:${{ steps.env-tag.outputs.tag }}
            ghcr.io/joeyhofman/webdev-showcase-client:${{ github.sha }}
