name: Frontend CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: joeyhofman/webdev-showcase-client

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VITE_BACKEND_API_URL=https://api.diagramming.com/
          tags: |
            ghcr.io/joeyhofman/webdev-showcase-client:${{ github.sha }}
  test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://test.diagramming.com
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: imjasonh/setup-crane@v0.4
      - run: |
          crane tag \
            ghcr.io/joeyhofman/webdev-showcase-client@${{ needs.build.outputs.digest }} \
            test
  acceptance:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    environment:
      name: Acceptance
      url: https://acceptance.diagramming.com
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: imjasonh/setup-crane@v0.4
      - run: |
          crane tag \
            ghcr.io/joeyhofman/webdev-showcase-client@${{ needs.build.outputs.digest }} \
            acceptance
  production:
    needs:
      - build
      - test
      - acceptance

    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://diagramming.com

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: imjasonh/setup-crane@v0.4

      - run: |
          crane tag \
            ghcr.io/joeyhofman/webdev-showcase-client@${{ needs.build.outputs.digest }} \
            production
